services:

  db:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./mydata/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_SERVER={$POSTGRES_SERVER?Variable not set}
      - POSTGRES_USER={$POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB={$POSTGRES_DB?Variable not set}
    networks:
      - network-db
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.9
    networks:
      - network-db
    environment:
      - PGADMIN_DEFAULT_EMAIL={$PGADMIN_DEFAULT_EMAIL?Variable not set}
      - PGADMIN_DEFAULT_PASSWORD={$PGADMIN_DEFAULT_PASSWORD?Variable not set}
    ports:
      - 5433:80
    volumes:
      - ./mydata/pgadmin/data:/var/lib/pgadmin
    restart: always


networks:
  network-db:
    driver: bridge
    internal: true
