name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#      - name: GPT代码逻辑检查
#        uses: anc95/ChatGPT-CodeReview@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          # optional
#          LANGUAGE: Chinese
##          PROMPT:
      - name: checkout
        uses: actions/checkout@v4
      - name: python编码风格检查
        uses: wemake-services/wemake-python-styleguide@master
        with:
            reporter: 'terminal'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
