name: ansible-lint

on:
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: 代码安全检查
    steps:
      - uses: actions/checkout@v4
      - name: 运行 PyCharm 安全性
        uses: tonybaloney/pycharm-security@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
