name: ansible-lint
on:
  push: null
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v4
      - name: 运行 PyCharm 安全性
        uses: tonybaloney/pycharm-security@master
